### ISSUE TITLE
Feature request: Lane Line Detection for Autonomous Vehicles

### ISSUE THREAD

**Issue by aviralgarg05** [UppuluriKalyani/ML-Nexus#100]
**Is your feature request related to a problem? Please describe.**
Lane Line Detection for Autonomous Vehicles

**Describe the solution you'd like**
Use OpenCV and Machine Learning Algorithms to Find Lane Lines

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
Training on Video Datasets, Labelling the Lane Lines and Testing on Test Videos and Images

**Additional context**
I am a GSSOC'24 Extended and Hacktoberfest Contributor

**Comment by SaiNivedh26** [comment]
You can start working
