### ISSUE TITLE
Face Recognition System

### ISSUE THREAD

**Issue by anirudh-248** [UppuluriKalyani/ML-Nexus#101]
# Title: Face Recognition System
The Facial Recognition System is designed to detect and recognize faces in real-time using a combination of the Ultralytics YOLO model, the face_recognition library, and OpenCV for live video processing. The system utilizes supervised learning by training on a labeled dataset of known faces, where each face is associated with an identity. The project creates a pipeline that detects faces from a live video feed, extracts facial features, and matches them against the labeled dataset for identification. The system effectively classifies faces based on learned features by using YOLO for object detection and face_recognition for embedding extraction and comparison. This project is ideal for real-time surveillance, security, and access control applications.
Kindly assign this project to me @UppuluriKalyani 

Name: Anirudh P S || GSSOC'24 EXT / HACKTOBERFEST

**Comment by SaiNivedh26** [comment]
You can start working

**Comment by vishalmaurya850** [comment]
Please assign this issue to me as I have great experience in working with projects of Data Science and Machine Learning
