### ISSUE TITLE
Feature request : Fire Detection using YOLOv8 

### ISSUE THREAD

**Issue by rugved0102** [UppuluriKalyani/ML-Nexus#114]
**Is your feature request related to a problem? Please describe.**
Fire Detection using YOLOv8
This project demonstrates how to use the YOLOv8 object detection model to detect fire in images. It loads a pre-trained YOLOv8 model, processes the input image, and identifies fire regions. The results are displayed with bounding boxes around detected fire areas, and the processed image is saved for further analysis.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**

**Comment by UppuluriKalyani** [comment]
@rugved0102 already someone did.
