### ISSUE TITLE
Feature request Real Time Monitoring of Construction Site

### ISSUE THREAD

**Issue by Pseudophoenix** [UppuluriKalyani/ML-Nexus#119]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Real time construction site monitoring using Web based Interface and Yolo based multiple models for category of objects and persons. Providing stats like number of workers, machinery working or not, and predicting completion time based on logs of progress of construction.

**Describe the solution you'd like**
Will be adding a whole project of real time construction site monitoring system that using various ML concepts starting from basic supervised models ensembled to give a good aggregate, CNN architectures, and even fine-tuned models.

**Describe alternatives you've considered**
There can be many alternatives like those available in Object detection using Yolos or Hugging Face.

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
I will try to even deploy it on web cam and proper data transfer making use of other tech tools for interface, backend and deployment

**Comment by Pseudophoenix** [comment]
Mam I wanted to add this project. Why have you closed this project?

**Comment by UppuluriKalyani** [comment]
Someone already did this ig.
