### ISSUE TITLE
 Real-Time Suspicious Activity Detection System for Retail Stores

### ISSUE THREAD

**Issue by UppuluriKalyani** [UppuluriKalyani/ML-Nexus#131]
This project leverages computer vision and deep learning to detect suspicious activities within retail stores.

Input:
The input consists of real-time video feeds from surveillance cameras placed within the store. The system processes frames of the video, detecting people and their movements.

Processing:
The video frames are analyzed using object detection algorithms, human posture recognition, and behavior prediction models. The system assigns probabilities to various actions (e.g., walking, standing, putting items in pockets) using deep learning techniques to recognize suspicious behavior.

Output:
The output is an annotated video feed with bounding boxes around individuals, accompanied by labels and probability scores indicating detected actions (e.g., "Walking: 75.73%", "Item in pocket: 77%"). This allows store managers to monitor activities and flag potential theft or unusual behavior in real-time.
![Screenshot_20241007_175722_LinkedIn](https://github.com/user-attachments/assets/322b06e1-88c2-42e1-bbb0-53b5b1c0e8c8)

**Comment by Pranshu-jais** [comment]
@UppuluriKalyani   please assign this issue to me

**Comment by UppuluriKalyani** [comment]
@Pranshu-jais proceed!

**Comment by JahnaviDhanaSri** [comment]
Hi @UppuluriKalyani,

I am very interested in contributing to this project on real-time suspicious activity detection! The integration of computer vision and deep learning for retail security is a compelling challenge, and I have experience with object detection and behavior analysis using deep learning techniques. I believe I can effectively help implement the algorithms and features needed for this system.

Could you please assign this issue to me?
