### ISSUE TITLE
Streamlit Web Application for Medical Research Text Extraction

### ISSUE THREAD

**Issue by DebanKsahu** [UppuluriKalyani/ML-Nexus#132]
Project:- SkimLit
Issue:-  It is a new project that I want to add under the issue number #19
Aim:- The aim of the project is to create a streamlit web add which use my personal modified models (based on SkimLit) to extract information from any medical research in form of 5 different paragraph which are 
background,objective,methods,results,conclusion.

**Comment by DebanKsahu** [comment]
@UppuluriKalyani  how is this??

**Comment by UppuluriKalyani** [comment]
@DebanKsahu go ahead
