### ISSUE TITLE
AI-Powered News Summarizer and Sentiment Analyzer

### ISSUE THREAD

**Issue by UppuluriKalyani** [UppuluriKalyani/ML-Nexus#145]
### AI-Powered News Summarizer and Sentiment Analyzer

**Description**:

Develop a web application using Streamlit that takes in news articles, extracts the main points, and provides a concise summary. Additionally, the application will analyze the sentiment (positive, negative, or neutral) of the news articles, providing insights on the overall tone. This can help users quickly grasp the essence and emotional direction of trending news topics.

**Key Features**:

Input: Users can provide links to news articles or paste text directly.

Text Summarization: Using NLP models (like BART, T5, or GPT), the tool will generate a brief summary.

Sentiment Analysis: Classify the article's sentiment (positive, negative, or neutral) using models like BERT or Vader.

Category Detection: Automatically detect the category (e.g., politics, technology, health) of the article.

Trending Topic Insights: Display popular topics based on current news trends.

**Tech Stack**:

Frontend: Streamlit

Backend: Python, NLP models (Hugging Face transformers for summarization and sentiment analysis)

APIs: Use news APIs (like NewsAPI) to fetch real-time articles for users to analyze.

**Comment by gos24abhik** [comment]
@UppuluriKalyani 
Assign me this project.
I am very excited about the opportunity to contribute to the AI-Powered News Summarizer and Sentiment Analyzer project. The concept of utilizing NLP to enhance news consumption is fascinating, and I believe it has the potential to provide significant value to users.

I have experience working with Streamlit and various NLP models from Hugging Face.
