### ISSUE TITLE
Feature request - Spoken Language Translator

### ISSUE THREAD

**Issue by ramana2074** [UppuluriKalyani/ML-Nexus#150]
**Is your feature request related to a problem? Please describe.**
 The goal of this project is to develop a robust language translator that can accurately detect the language of the input text and translate it into the desired language. 

**Describe the solution you'd like**
I want the language translator to:

Automatically detect the language of the input text.
Provide a seamless translation of the input into the selected language using advanced machine learning and natural language processing techniques.
Offer a simple and intuitive user interface where users can input text and select the desired language.
Utilize the Google Translate API for reliable and accurate translations, supporting a wide range of languages.

**Describe alternatives you've considered**
Using other translation APIs like Microsoft Translator API or DeepL Translator API. However, Google Translate was chosen due to its accuracy, broad language support, and familiarity.
Developing an entirely custom machine learning model for language translation, but this would require a significant amount of data and resources, which is beyond the current scope of the project.

**Approach to be followed (optional)**

Language Detection: Use the Google Translate API to automatically detect the language of the input text.
Translation: Leverage pre-trained translation models provided by the Google Translate API for efficient translations.
User Interface: Develop a web interface using Flask where users can input text and select the target language.
Integration: Integrate the front-end and back-end components to ensure a smooth workflow for translating text.
Additional Features: In the future, consider adding features like text-to-speech and support for multilingual texts.

**Additional context**
This project utilizes Python and the Google Translate API to detect and translate text. It also incorporates Flask to build a user-friendly web interface and uses natural language processing libraries such as NLTK for handling language-related tasks.

**Comment by JahnaviDhanaSri** [comment]
Hi @ramana2074,

I am highly interested in contributing to this project! With my experience in natural language processing (NLP) and web development using Flask, I believe I can help implement the language detection and translation features effectively. I also have worked with APIs like Google Translate, which will make integration smoother.

Could you please assign this issue to me?

**Comment by JahnaviDhanaSri** [comment]
Hi @ramana2074,

I find the idea of developing a spoken language translator very exciting! The approach to utilize the Google Translate API for language detection and translation sounds solid, and I believe my skills in Python and web development can greatly contribute to this project.

Could you please assign this issue to me?

**Comment by ramana2074** [comment]
hi @JahnaviDhanaSri 
I would be doing this by using the Tkinter library for the GUI, googletrans for translation, win32com.client for text-to-speech (TTS), and speech_recognition for speech-to-text conversion. I am not much familiar with web development after may be this feature gets merged you can raise another issue to enhance this and am not the person who can assign it so let's wait until it is assigned.

**Comment by JahnaviDhanaSri** [comment]
Ok
