### ISSUE TITLE
Feature request  # Feature Using Computer Vision to Detect Bad Posture 

### ISSUE THREAD

**Issue by praveenarjun** [UppuluriKalyani/ML-Nexus#153]
:red_circle: **Title** : Computer Vision to Detect Bad Posture
:red_circle: **Aim** : Implement a feature using computer vision techniques to detect bad posture in real-time using a webcam feed.
:red_circle: **Brief Explanation** : The feature will leverage machine learning models to analyze the user's posture through a webcam feed. It will provide real-time feedback and suggestions to correct posture, helping users avoid potential health issues associated with bad posture. The implementation will involve training a posture detection model, integrating it with the PyVerse project, and creating a user-friendly interface for real-time monitoring and feedback.

### Screenshots 📷
![postur](https://github.com/user-attachments/assets/e232b4db-0a3e-419a-beaf-24df753f2f9b)

**Comment by praveenarjun** [comment]
can you pls add the level

**Comment by Neilblaze** [comment]
closing via #171
