### ISSUE TITLE
Time Series Analysis using ARIMA for stock prediction

### ISSUE THREAD

**Issue by DarshAgrawal14** [UppuluriKalyani/ML-Nexus#162]
Hey @UppuluriKalyani , 
I would like to contribute by adding a time series analysis model for stock prediction as most the models found on internet use LSTM or other regression models and do not take the day of exchange into account . This model by taking date and dividing it into day, month and  year along with lags. A dataset found on internet was upgraded to support time series analysis and a ARIMA model is trained on it.

**Comment by DarshAgrawal14** [comment]
Time series analysis is part of advanced deep learning and just training in usual datasets dont work in time series analysis . please update to level2 atleast as this task took a lot of time in comparison to level 1 tasks

**Comment by UppuluriKalyani** [comment]
@DarshAgrawal14 show me the implementation then will see.
