### ISSUE TITLE
Emotion Detection + Pose Detection

### ISSUE THREAD

**Issue by akashlogics** [UppuluriKalyani/ML-Nexus#166]
**Is your feature request related to a problem? Please describe.**
# Emotion Detection + Pose Detection
It can be used to check for violence in any area with the help of CCTV Cameras. Violence is an urgent public health problem. From infants to the elderly, it affects people in all stages of life and can lead to a lifetime of physical, emotional, and economic problems.

**Describe the solution you'd like**
### Libraries Used:
- OpenCV
- MediaPipe
- DeepFace

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
<img width="1440" alt="sample outputs" src="https://github.com/user-attachments/assets/c9902808-7d00-4bd5-8d57-50f904291e9d">

**Comment by UppuluriKalyani** [comment]
@akashlogics Go ahead!
