### ISSUE TITLE
Book recommendation system

### ISSUE THREAD

**Issue by shalini-bhandari** [UppuluriKalyani/ML-Nexus#174]
**Is your feature request related to a problem? Please describe.**
With the vast number of books available across various genres, platforms, and formats, users often find it overwhelming to discover books that match their interests. Hence the recommendation system

**Describe the solution you'd like**
To develop a Collaborative Filtering book recommendation system that utilizes user ratings, reviews, and community interactions to suggest books that similar users have enjoyed

@UppuluriKalyani kindly assign me this under gssoc-ext and hacktoberfest-accepted with level2

**Comment by JahnaviDhanaSri** [comment]
Hi @shalini-bhandari,

I’m really interested in the Book Recommendation System feature request! I have experience in building collaborative filtering models and a strong understanding of recommendation systems, which I believe will be valuable in developing this project.

Could you please assign this issue to me

**Comment by Neilblaze** [comment]
@shalini-bhandari go for it! Don't forget to add a README file to your PR (including images are generally recommended) for reference.
