### ISSUE TITLE
Feature request:pneumonia detection 

### ISSUE THREAD

**Issue by 17arindam** [UppuluriKalyani/ML-Nexus#183]
**Is your feature request related to a problem? Please describe.**
I want to add a model which will detect pneumonia using chest xray
**Describe the solution you'd like**
A custom CNN model is created for pneumonia classification.
The model is trained and evaluated on the same dataset.
![image](https://github.com/user-attachments/assets/948e25b1-b597-405b-a373-ab09ba9e4849)

**Comment by UppuluriKalyani** [comment]
@17arindam Go ahead!
