### ISSUE TITLE
Pipeline to predict whether given pdf is malacious or not

### ISSUE THREAD

**Issue by DarshAgrawal14** [UppuluriKalyani/ML-Nexus#198]
Hey @UppuluriKalyani ,
I would like to contribute by developing a pipeline that, when provided with a PDF, extracts metadata, content, and other relevant features. These extracted elements are then processed and passed to a model, which predicts whether the PDF is malicious.
Additions:
-  Model Training notebook
-  Pdf feature extraction notebook
-  Data processing and model prediction notebook
-  Dataset used
-  Trained Model

**Comment by UppuluriKalyani** [comment]
@DarshAgrawal14 proceed!
