### ISSUE TITLE
Student Performance using XGBoost and CatBoost

### ISSUE THREAD

**Issue by ayushijainn111** [UppuluriKalyani/ML-Nexus#206]
**Is your feature request related to a problem? Please describe.**
It is a student performance analysis using XGBoost and CatBoost

**Describe the solution you'd like**
Here, we check how different factors affect students academic performance and how can one deal with it.

**Describe alternatives you've considered**
checking the feature parameters and the factors affecting the growth.

**Approach to be followed (optional)**
data preprocessing, EDA, feature analysis, feature engineering, XGBoost and CatBoost.

**Additional context**
It would be great if i could contribute!

**Comment by UppuluriKalyani** [comment]
@ayushijainn111 proceed!
