### ISSUE TITLE
Style Transfer with Neural Networks

### ISSUE THREAD

**Issue by alo7lika** [UppuluriKalyani/ML-Nexus#209]
### **Is your feature request related to a problem? Please describe.**
Currently, to adjust parameters such as `content_weight`, `style_weight`, and `num_steps`, users have to rerun the entire style transfer process in the Jupyter Notebook. This makes it time-consuming to fine-tune the model and achieve the desired results, especially for users experimenting with different settings.

### **Describe the solution you'd like**
I would like the ability to dynamically adjust parameters like `content_weight`, `style_weight`, and `num_steps` without restarting the entire model training process. This can be done using interactive widgets within the Jupyter Notebook, allowing users to modify values and see the resulting style transfer output in real time.

### **Describe alternatives you've considered**
One alternative could be building a command-line interface (CLI) tool where users can pass parameters as arguments to the script and perform style transfer without modifying the code in the notebook. Another option would be to create a web interface that allows for interactive image uploading and parameter adjustments.

### **Approach to be followed (optional)**
To implement this feature, we could use IPython widgets, which are integrated with Jupyter Notebooks, to allow users to interactively update parameters such as weights and optimization steps. This would provide instant feedback by updating the output image dynamically without restarting the notebook kernel.

### **Additional context**
This feature would improve the user experience by making the model more accessible to non-experts who may want to experiment with different styles and configurations quickly. Below is an example of how the interactive widget might look:

**Comment by UppuluriKalyani** [comment]
@alo7lika proceed
