### ISSUE TITLE
Flight fare prediction app

### ISSUE THREAD

**Issue by Aditijainnn** [UppuluriKalyani/ML-Nexus#237]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
 build a Python Flight Fare Prediction App, that returns the fare prediction for a given set of travel details, like: departure date, arrival date, departure city, arrival city, stoppages

Assign this to me under gssoc ext and hacktoberfest

**Comment by Panchadip-128** [comment]
I can take this project and contribute via focussing on predicting flight prices using machine learning techniques, specifically employing the RandomForestRegressor from scikit-learn. The dataset used will contain comprehensive flight details sourced from Kaggle, including airline information, source and destination cities, flight duration, total stops, and ticket prices. i have completed the project and contains high degree of efficient ml models and algorithms and analysis

Assign this to me under gssoc ext and hacktoberfest
