### ISSUE TITLE
Interview Questions based on Resume Using Generative AI and Machine Learning

### ISSUE THREAD

**Issue by rithvikreddybasani** [UppuluriKalyani/ML-Nexus#264]
I have developed a Website which takes resume as input and provide useful interview Questions based on Resume.

And it will also give Suggestions based on our Resume.

![image](https://github.com/user-attachments/assets/c793affb-45b1-4b0e-a88d-3265e60aba29)

@UppuluriKalyani, @Neilblaze,@SaiNivedh26   can you assign me this?

**Comment by UppuluriKalyani** [comment]
@rithvikreddybasani Assigned!
