### ISSUE TITLE
Develop a Gesture-Controlled Virtual Calculator with Trigonometric Operations

### ISSUE THREAD

**Issue by UppuluriKalyani** [UppuluriKalyani/ML-Nexus#27]
**Description**:
This project involves creating a gesture-controlled virtual calculator where users can perform basic arithmetic and trigonometric calculations using hand gestures instead of a traditional keyboard or mouse. By waving their hands in front of a camera, the system will recognize specific gestures linked to mathematical operations. Additionally, for trigonometric functions, users can draw shapes (like triangles, squares, circles) to perform operations like sine, cosine, and tangent calculations based on the shapes they create. An AI component will interpret the shapes and perform the corresponding trigonometric operations.
**Task Overview**:

- Implement hand gesture recognition to control a virtual calculator that performs basic operations (addition, subtraction, multiplication, division).

- Extend gesture recognition to support trigonometric operations by detecting shapes (e.g., triangle for sine/cosine, square for area calculations).

- Connect an AI module to interpret the drawn shapes and calculate trigonometric values or perform other geometry-related operations.

- Display the calculations and results on a virtual calculator interface.

**Comment by Pranshu-jais** [comment]
I want to contribute to this project  as gssoc-ext contributor . please assign this issue to me.

**Comment by UppuluriKalyani** [comment]
@Pranshu-jais Go ahead!

**Comment by Pranshu-jais** [comment]
thanks for assigning the issue to me

> @Pranshu-jais Go ahead!

**Comment by KartikSaxena19** [comment]
If this issue is not solved yet you can assign this issue to me

**Comment by UppuluriKalyani** [comment]
@KartikSaxena19 yes proceed!

**Comment by KartikSaxena19** [comment]
Can i still solve this issue or you close this request

**Comment by UppuluriKalyani** [comment]
> Can i still solve this issue or you close this request

He is already solved if you want to try differently with more features you can do it
