### ISSUE TITLE
Getting Admission in College Prediction

### ISSUE THREAD

**Issue by ramana2074** [UppuluriKalyani/ML-Nexus#284]
**Is your feature request related to a problem? Please describe.**
Predicting whether the admission might happen in the college.

**Describe the solution you'd like**
 By using Different ML Techniques likes Linear regression, lasso, svr, decision trees. Choosing the best technique and predicting the college admission.

**Approach to be followed (optional)**
By attaining the different accuracies of different ML techniques and choosing the best one to predict.

**Comment by UppuluriKalyani** [comment]
@ramana2074 
Please check if your total contributions to my repository have exceeded 200 points. If they have, we won't be able to accept further contributions, and any new contributions you make won't be reflected on the leaderboard as per GSSOC guidelines.
If not you can continue.

**Comment by ramana2074** [comment]
No it did not exceeded 200 points

**Comment by ramana2074** [comment]
I have already contributed, and merging is also done. you can close this issue.
