### ISSUE TITLE
Anomaly detection in network traffic

### ISSUE THREAD

**Issue by ojhankit** [UppuluriKalyani/ML-Nexus#292]
Objective: Detect unusual or potentially malicious network traffic patterns using unsupervised learning.

Steps
1.gather dataset from kaggle on network traffic
2. Basic preprocessing like normalization
3. Feature selection
4. Models like isolation forest, dbscan will be used in this project.

**Comment by ojhankit** [comment]
@Neilblaze could you please assign this to me

**Comment by UppuluriKalyani** [comment]
@ojhankit proceed
