### ISSUE TITLE
Feature request: I would like to build a chatbot using RAG and LLMs

### ISSUE THREAD

**Issue by infinity-void6** [UppuluriKalyani/ML-Nexus#305]
I would like to build a RAG bot for the topic under Generative Models for a particular website

Requirements:
LLM API key/ HuggingFace
Flask/FastAPI for UI
Beuatiful Soup for crawling website

Approaches used:
1)web crawling
2)embedding the content
3)Vector Database and RAG
4)Serving the bot

**Comment by UppuluriKalyani** [comment]
@infinity-void6 proceed
