### ISSUE TITLE
[Feature request] Development of Electrical and Electronics Shop Finder

### ISSUE THREAD

**Issue by J-B-Mugundh** [UppuluriKalyani/ML-Nexus#336]
**Is your feature request related to a problem? Please describe.**
Currently, there is no dedicated tool that allows users to easily find and locate electrical and electronics shops in their vicinity using a map interface. Users often struggle to find reliable shops, which leads to frustration and wasted time searching for them.

**Describe the solution you'd like**
I propose developing an Electrical and Electronics Shop Finder application that leverages the capabilities of Gemini for data retrieval, Mapbox for visualization, and Plotly for interactive mapping. The solution should include:

- Location-Based Search: Users can enter their location to find nearby electrical and electronics shops.
- Interactive Map Display: Use Mapbox to plot the locations of these shops on an interactive map.
- Detailed Information: Each shop entry should provide essential details, such as the shop name, address, latitude, longitude, and a direct link to Google Maps for easy navigation.

**Describe alternatives you've considered**
.

**Approach to be followed (optional)**

- API Integration: Utilize the Gemini API to gather data on electrical and electronics shops based on user input.
- Data Processing: Extract relevant information (shop name, location, links) and format it for visualization.
- Map Integration: Use Mapbox to render an interactive map that displays the shop locations, allowing users to hover over markers for additional information.
- Testing: Conduct user testing to ensure the application is intuitive and meets user needs

**Additional context**
Implementing this feature will greatly enhance the user experience by providing a seamless way to find and visualize nearby electrical and electronics shops, ultimately saving time and improving accessibility.

I'm a gssoc-extd contributor

**Comment by J-B-Mugundh** [comment]
Hi @UppuluriKalyani, considering the benefits of this feature and it's approach, it should be level 2 atleast. I can build a streamlit app or backend with flask and any frontend stack like HTML or React. Please consider it. You can see the results when I raise PR.

**Comment by UppuluriKalyani** [comment]
> Hi @UppuluriKalyani, considering the benefits of this feature and it's approach, it should be level 2 atleast. I can build a streamlit app or backend with flask and any frontend stack like HTML or React. Please consider it. You can see the results when I raise PR.

It's ok never mind labels on issues..I would change on PR based on your implementation.
