### ISSUE TITLE
Multi Modal RAG for avoiding the hallucinations to some extenet .....

### ISSUE THREAD

**Issue by chakka-guna-sekhar-venkata-chennaiah** [UppuluriKalyani/ML-Nexus#356]
The main problem with the traditional RAG was hallucination if our data source contains different types of data rather than text. Especially if the data sources cotains tables as images , the RAG system needs to work very well. I have a solution to solve this to some extent using unstructured.io methods. 

@Neilblaze @UppuluriKalyani @SaiNivedh26

**Comment by chakka-guna-sekhar-venkata-chennaiah** [comment]
what does the following question mean?
```
Attach before & after screenshots in your PR for clarity.
```
@UppuluriKalyani @SaiNivedh26  @Neilblaze

**Comment by UppuluriKalyani** [comment]
> what does the following question mean?
> 
> ```
> Attach before & after screenshots in your PR for clarity.
> ```
> 
> @UppuluriKalyani @SaiNivedh26 @Neilblaze 
Results

**Comment by UppuluriKalyani** [comment]
> > > what does the following question mean?
> > > ```
> > > Attach before & after screenshots in your PR for clarity.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @UppuluriKalyani @SaiNivedh26 @Neilblaze



> > what does the following question mean?
> > ```
> > Attach before & after screenshots in your PR for clarity.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @UppuluriKalyani @SaiNivedh26 @Neilblaze


Results

**Comment by UppuluriKalyani** [comment]
@chakka-guna-sekhar-venkata-chennaiah Screenshots of your implementation results.
before and after mean if you find any bug or something you should show it like before it looks like this after update it looks like this.

**Comment by chakka-guna-sekhar-venkata-chennaiah** [comment]
@UppuluriKalyani Can we add the scratch project for the raised issue instead of solving the bug? Because i want to contribute that project to this repo.

**Comment by UppuluriKalyani** [comment]
> @UppuluriKalyani Can we add the scratch project for the raised issue instead of solving the bug? Because i want to contribute that project to this repo.

Yes you can I'm just saying if it is bug then you should do like that if it is feature just show me the results.

**Comment by chakka-guna-sekhar-venkata-chennaiah** [comment]
@UppuluriKalyani  I thought that open source contribution means creating new projects that's why I raised the pr. But later you informed that I need to change or add the functionality of any existing project right. That's why I'm deciding to delete my pr's
