### ISSUE TITLE
Building WhatsApp Based RAG BOT  (free to use) for UPSC Students 

### ISSUE THREAD

**Issue by chakka-guna-sekhar-venkata-chennaiah** [UppuluriKalyani/ML-Nexus#357]
I want to make an free WhatsApp Chatbot for the UPSC Students. Students can easily get the answers from their syllabus, they can also check their knoweldge with the bot, also the bot has the window mechanism where the user can question fromt the chat history etc.

@UppuluriKalyani  @SaiNivedh26  @Neilblaze

**Comment by UppuluriKalyani** [comment]
@chakka-guna-sekhar-venkata-chennaiah Assigned
