### ISSUE TITLE
Project " An Azure AI  Sentiment analyzer"

### ISSUE THREAD

**Issue by priyans877** [UppuluriKalyani/ML-Nexus#37]
**Is your feature request related to a problem?.**
In now days where online shopping culture is in boom & approxly more then 50% of people now give thier review which will give an huge impact on the product sales.

**Describe the solution you'd like**
We can implement an Azure based Ai solution that can Analyze user reviews by taking input with various methods like :  Input by user , uploading File . or By speak .
it will give outtut : Language,Sentiment , Key phrases, Entities etc
These Thing will give insights that which  enitty will have an huge negative or positive  impact on the review 

I will be complete this project , kindly assign it 
Thanking you

**Comment by UppuluriKalyani** [comment]
@priyans877 go ahead!

**Comment by SaiNivedh26** [comment]
@priyans877 can you share the progress of this project ?
