### ISSUE TITLE
Feature request finding postive and negative score by NLP

### ISSUE THREAD

**Issue by akashlogics** [UppuluriKalyani/ML-Nexus#39]
**Is your feature request related to a problem? Please describe.**
yes, I had scripted data of multiple articles from a website blackcoffer and performed NLP process in it 

**Describe the solution you'd like**
I used beautiful soup and request for web scraping and NlP calculations like
**POLARITY SCORE**
**SUBJECTIVITY SCORE**
**AVG SENTENCE LENGTH**
**PERCENTAGE OF COMPLEX WORDS**
**.FOG INDEX**
**AVG NUMBER OF WORDS PER SENTENCE**
**COMPLEX WORD COUNT**
**WORD COUNT**

**Describe alternatives you've considered**
can also find common words used in articles

**Approach to be followed (optional)**
please assign me this issue so I can add my project for others to learn basics of NLP 
label **gssoc-extd and hacktoberfest** 

**Additional context**

**Comment by UppuluriKalyani** [comment]
@akashlogics go ahead!
