### ISSUE TITLE
Add New Project: Real-Time Object Counter Streamlit App - YOLOv8 + OpenCV

### ISSUE THREAD

**Issue by rakheshkrishna2005** [UppuluriKalyani/ML-Nexus#396]
## **Is your feature request related to a problem? Please describe**
Real-Time Object Counter Streamlit app can count the object from the video feed or webcam and display the real-time results. It has various use cases to solve real-world problems. Example: Crowd monitoring, traffic management.

## **Solution Description**
I have built the app using streamlit and the tech stack is Python, YOLOv8, OpenCV, PyTorch.

## **Alternatives I have considered**
Alternative tech stack: App can also be built with HTML, CSS, JS, Flask

## **Approach to be followed**
Tech Stack: `app.py`, `main.css`, `yolov8n.pt`, `run.bat`, `README.md`
Install `requirements.txt`, them just click `run.bat`. Your app is running now.

## **Demo Video**
https://github.com/user-attachments/assets/8e86dca8-5afb-451c-a5cc-9bf2b99bac5a

**Comment by UppuluriKalyani** [comment]
@rakheshkrishna2005 Assigned
