### ISSUE TITLE
Feature request Accident Classifier

### ISSUE THREAD

**Issue by Pseudophoenix** [UppuluriKalyani/ML-Nexus#41]
**Is your feature request related to a problem? Please describe.**
Typically related to computer vision and transfer learning, I will be fine tuning the Yolov7 to classify images into severe accident and moderate accident

**Describe the solution you'd like**
I will be using the yolov7 weights and then after freezing the base layer and modifying the upper layers to serve my purpose of accident severity classification.

**Describe alternatives you've considered**
I also thought of instead going with ResNet50 fine tuning but Yolov7 seems a better option for now. I will try to go with ResNet as well through PyTorch.

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
I will be using this annotated Roboflow image dataset.
https://universe.roboflow.com/accident-detection-model/accident-detection-model

Hope this will be assigned to me in the fine tuning section

**Comment by UppuluriKalyani** [comment]
@Pseudophoenix go for it!
