### ISSUE TITLE
visual question answering chatbot

### ISSUE THREAD

**Issue by BhavyaFattania** [UppuluriKalyani/ML-Nexus#43]
A visual question answering model is model in which computer vision and natural language processing is done at the same time.

It is a type of chatbot in which user will upload image and will ask relevent questions regarding uploaded image and chatbot will answer those questions.

I think this is different as it includes integration between natural language processing tasks and computer vision task. Integrating both to form a single working model would be a step above normal conversational chatbots.

May be we could add a new folder named multimodel which includes multimodel AI like this and many more.

**Comment by BhavyaFattania** [comment]
I am doing this for GSSOC 2024 EXTD, but dont know gssoc-ext label is not appearing, pls guide me

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania go ahead!
