### ISSUE TITLE
(Image to text) image captioning model

### ISSUE THREAD

**Issue by BhavyaFattania** [UppuluriKalyani/ML-Nexus#44]
(Image-to-text) image captioning model is missing in computer vision repository.
this type of model creates conditional and un-conditional captions based on the image user has uploaded.

this could be very useful when describing image without even looking at the image
![Screenshot 2024-10-02 023131](https://github.com/user-attachments/assets/755eeae5-9867-4986-bb98-e631716b65c7)

**Comment by BhavyaFattania** [comment]
this is preview of model, It works like that and conditional and uncontitional output is generated like it appears in the image

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania Go for it!

**Comment by BhavyaFattania** [comment]
@UppuluriKalyani code is ready how should I submit now

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania Make pull request.

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania yes keep the implementation under computer vision folder with all required files
i.e implementation, Readme,results, requirements,model etc.

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania yes and also implementation of the project

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania yes

**Comment by BhavyaFattania** [comment]
It will be completed till yestersay

**Comment by BhavyaFattania** [comment]
Yesterday*
