### ISSUE TITLE
A speech emotion recognition

### ISSUE THREAD

**Issue by Vishisht16** [UppuluriKalyani/ML-Nexus#45]
A propose adding a Speech Emotion Recognition model. Basically, a deep learning model will take audio input, process it and classify the tone of speaking as angry, calm, happy, etc.

I'll be using various large speech datasets to train the model. This would be a great addition to the current and upcoming features.

I hope this gets assigned to me

**Comment by UppuluriKalyani** [comment]
@Vishisht16 Proceed!

**Comment by Vishisht16** [comment]
Hi! I believe this should be a level 3 issue.
I'm done with it but may I have your opinion first?

**Comment by UppuluriKalyani** [comment]
@Vishisht16 first show me the implementation then I will decide

**Comment by UppuluriKalyani** [comment]
@Vishisht16 Hey share you insta profile once

**Comment by Vishisht16** [comment]
Hi @UppuluriKalyani , I'm sorry I was unavailable because of job and exam
My insta username is vishishtmishra 
I'll drop the pull request later today
Thanks a lot for your patience

**Comment by UppuluriKalyani** [comment]
> Hi @UppuluriKalyani , I'm sorry I was unavailable because of job and exam My insta username is vishishtmishra I'll drop the pull request later today Thanks a lot for your patience

I asked for Linkedln Profile

**Comment by Vishisht16** [comment]
Oh, I read your comment through mail
Here's my [https://www.linkedin.com/in/vishisht-mishra](linkedin) profile

**Comment by Vishisht16** [comment]
https://www.linkedin.com/in/vishisht-mishra
