### ISSUE TITLE
Crater Detection Model for Lunar Surface

### ISSUE THREAD

**Issue by Kaibalya27** [UppuluriKalyani/ML-Nexus#451]
**Is your feature request related to a problem? Please describe.**
Accurate detection of lunar craters, especially in low-light regions like PSR (Permanently Shadowed Regions), is crucial for enhancing surface mapping and identifying potential landing sites. Current models can benefit from a specialized crater detection approach tailored for the lunar environment.

**Describe the solution you'd like**
This model would use advanced object detection techniques to automatically identify and highlight craters, making it easier to analyze lunar surface features. By optimizing it for lunar conditions, the model will enhance surface mapping efforts and assist in locating safe landing sites for future missions.

**Comment by Kaibalya27** [comment]
hey @UppuluriKalyani ,

I have thoroughly searched the open issues but couldn't find any that closely resemble my request for a crater detection model.

Since I believe this feature would greatly benefit the project, may I proceed with my original issue? If needed, I'm happy to provide additional details or clarify any points.

**Comment by UppuluriKalyani** [comment]
@Kaibalya27 proceed
