### ISSUE TITLE
Multimodal Visual Question and answering model using BLIP

### ISSUE THREAD

**Issue by Panchadip-128** [UppuluriKalyani/ML-Nexus#460]
**Is your feature request related to a problem? Please describe.**
A tool that reads an image based on ML algorithms( BLIP model) and implements VQA which answers questions based on user prompts for the image, deployed through Gradio

**Describe the solution you'd like**
implementation of a Visual Question Answering (VQA) model built using the BLIP (Bootstrapping Language-Image Pre-training) framework. This model can understand image content and answer questions related to the provided images. A tool that reads an image based on ML algorithms( BLIP model) and implements Visual QA which answers questions based on user prompts for the image, deployed through Gradio web application

**Describe alternatives you've considered**
BLIP model architecture for VQA which can answer any questions related to a particular image prompt

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**

**Comment by Panchadip-128** [comment]
This issue i think is new and unique and isn't created till now

**Comment by UppuluriKalyani** [comment]
> This issue i think is new and unique and isn't created till now

Opened another issue check once
