### ISSUE TITLE
Feature request : Train a Model for Image Deblurring

### ISSUE THREAD

**Issue by DarshAgrawal14** [UppuluriKalyani/ML-Nexus#476]
**Is your feature request related to a problem? Please describe.**
Despite the prevalence of high-precision cameras, the world is full of low-quality, blurry images .It can be particularly useful in fields such as photography, medical imaging, and satellite imagery. Therefore , i want to develop a model that can deblur images 

**Describe the solution you'd like**
- Data preparation and processing
- Developing a multi-scale CNN or GAN model
- Implement various evaluation metrics such as Peak Signal-to-Noise Ratio (PSNR)
- Optimize the model for inference speed; create and deploy use-friendly web application

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**

**Comment by DarshAgrawal14** [comment]
@UppuluriKalyani , I couldn't find any issue referring to Image Deblurring.

**Comment by SaiNivedh26** [comment]
@DarshAgrawal14 if there's no corresponding issue, then create a new issue with detailed description of problem statement. We'll review and assign you. Then you can raise a pr
