### ISSUE TITLE
Image Style Transfer

### ISSUE THREAD

**Issue by Priyankasanyal04** [UppuluriKalyani/ML-Nexus#480]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Yes, Image Style Transfer  addresses a specific type of problem in the field of computer vision and image generation: combining the content of one image with the artistic style of another. NST solves the problem of rendering images in different artistic styles, making it possible to convert photographs into paintings or drawings while preserving key content elements. Automated creation of artistic visuals for media, advertising, and personal photography.
**Describe the solution you'd like**
1.Implementing neural style transfer using CNNs.
2.Loading a content image and a style image, then using a pre-trained model like VGG19   to extract features from both the content and style images and then combining them to generate the stylized output.
3.Applying this in creative projects, e.g., turning real-world images into artwork.

**Describe alternatives you've considered**
In addition to Neural Style Transfer (NST), here are alternative solutions and features that can achieve similar artistic or creative transformations in images:

1. GAN-based Style Transfer (Generative Adversarial Networks)
2.  Pre-trained Style Transfer Models (Fast Style Transfer)
3. Filter-based Image Manipulation

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
<img width="400" alt="input image" src="https://github.com/user-attachments/assets/c27b8fd0-9e81-48cb-92ff-a6ef8dc7e05b">
<img width="295" alt="output image" src="https://github.com/user-attachments/assets/6f241273-35a0-4cf7-bb50-0809dd986b89">

**Comment by coderhetal** [comment]
I m a gssoc extended contributor . Please assign this project to me .

**Comment by SaiNivedh26** [comment]
@coderhetal can you share the progress of this project ?
