### ISSUE TITLE
Segment Anything in Real Time

### ISSUE THREAD

**Issue by jaidh01** [UppuluriKalyani/ML-Nexus#484]
**Describe the solution you'd like**
To develop a model, where we can segment anything in real time.

We will use Fastsam for segmentation, because of its faster responses, in this we would be able to segment anything on an image.
The user will get 4 options: -segment everything, segment by box-prompt, point-prompt and text-prompt.

**Comment by jaidh01** [comment]
@UppuluriKalyani, there is no previous issue like this.
I request you to please review it once.

**Comment by jaidh01** [comment]
Hi @UppuluriKalyani , after reviewing the difficulty level of this task, I request you to please change the `level label` from `level 1` to `level 2`.

**Comment by UppuluriKalyani** [comment]
@jaidh01 I told you already never mind label levels on issues I would change it on PR based on your implementation.
