### ISSUE TITLE
Feature request:- Generate ML model data through video

### ISSUE THREAD

**Issue by jaidh01** [UppuluriKalyani/ML-Nexus#485]
**Describe the solution you'd like**
I propose the development of an interactive tool that allows users to record videos, manually label key points in the video, and automatically generate a CSV file with pose detection data for machine learning (ML) model training. This CSV will contain labeled keypoints, making it suitable for various pose-based ML tasks such as fitness tracking, sports performance, and yoga pose classification.

**Comment by jaidh01** [comment]
Hi @UppuluriKalyani , after reviewing the difficulty level of this task, I request you to please change the `level label` from `level 2` to `level 3`.

Thank you for your time.

**Comment by UppuluriKalyani** [comment]
> Hi @UppuluriKalyani , after reviewing the difficulty level of this task, I request you to please change the `level label` from `level 2` to `level 3`.

Yes will change based on your implementation don't worry

**Comment by jaidh01** [comment]
> > Hi @UppuluriKalyani , after reviewing the difficulty level of this task, I request you to please change the `level label` from `level 2` to `level 3`.
> 
> Yes will change based on your implementation don't worry

@UppuluriKalyani, Could you please consider it now?
