### ISSUE TITLE
Feature request- Parkinson's disease classification 

### ISSUE THREAD

**Issue by Shy029** [UppuluriKalyani/ML-Nexus#500]
I would like to raise a feature request for implementing Parkinson's disease classification using Support Vector Machine (SVM) as part of the ML Nexus project for GSSoC '24. Parkinson's is a complex neurodegenerative disorder, and early detection can significantly improve patient outcomes. SVM is an ideal algorithm for this task due to its ability to handle smaller datasets and complex feature spaces effectively. The model can utilize features like vocal patterns, motor functions, and tremor data to classify individuals with and without Parkinson's. Adding this feature to ML Nexus would not only enhance the project’s impact in healthcare but also provide contributors with a meaningful real-world application of machine learning in the medical field.

please assign this to me.

**Comment by ananyag309** [comment]
hi, since it's been 5 days and there has been no response from the person. Kindly asign this to me @UppuluriKalyani

**Comment by Shy029** [comment]
@UppuluriKalyani I had raised the PR related to it and it has been already merged to the main file.I have also received the mail regarding it.Kindly confirm it once.Please go through the Surpervised learning branch of the Project.

**Comment by UppuluriKalyani** [comment]
@Shy029 from Next time onwards when you are making PR please mention the issue no in the PR so that the issue will be closed after merging PR.

**Comment by UppuluriKalyani** [comment]
> hi, since it's been 5 days and there has been no response from the person. Kindly asign this to me @UppuluriKalyani

It is already done you can raise different ideas.

**Comment by Shy029** [comment]
@UppuluriKalyani Sure.And Sorry for this as I am new to open source .I am still learning.Thank you for giving me the chance to contribute!

**Comment by UppuluriKalyani** [comment]
> @UppuluriKalyani Sure.And Sorry for this as I am new to open source .I am still learning.Thank you for giving me the chance to contribute!

No problem
