### ISSUE TITLE
Create Deep Learning Model for Colourizing Old black and white Images

### ISSUE THREAD

**Issue by DarshAgrawal14** [UppuluriKalyani/ML-Nexus#502]
The idea of this project is to make a model that is capable of colorizing old black and white images to colorful images. Digital artists take a few hours to color the image but now with deep learning, it is possible to color an image within seconds.

**Comment by DarshAgrawal14** [comment]
@UppuluriKalyani , I didn't find any similar issues..

**Comment by UppuluriKalyani** [comment]
@DarshAgrawal14 #189
