### ISSUE TITLE
Feature request: Add a semantic segmentation python mini project in Computer Vision

### ISSUE THREAD

**Issue by mahipalimkar** [UppuluriKalyani/ML-Nexus#507]
I propose adding a Semantic Segmentation Module utilizing the U-Net architecture. This feature will enable pixel-wise segmentation, enhancing our repository's capabilities for applications in various domains like fashion and medical imaging.

Key Components:

U-Net Implementation: Integrate the U-Net architecture for efficient segmentation.
Data Handling: Leverage the existing VITON dataset class for seamless image and mask loading.
Training Pipeline: Utilize the train_fn function for model training, incorporating mixed precision and loss logging.
Evaluation Metrics: Include functions like check_accuracy for model performance monitoring.
Benefits:

Expands the functionality for users interested in semantic segmentation.
Provides a quick setup for training and evaluation on custom datasets.

**Comment by mahipalimkar** [comment]
Should I make a pr? @Neilblaze

**Comment by mahipalimkar** [comment]
@UppuluriKalyani can I make a pr?

**Comment by UppuluriKalyani** [comment]
> @UppuluriKalyani can I make a pr?

Yes you can
