### ISSUE TITLE
Music recommendation system

### ISSUE THREAD

**Issue by Ittismita** [UppuluriKalyani/ML-Nexus#54]
I want to add a ML model for recommending music.

A Music recommendation system.

Please assign me this issue under gssoc ext. and hacktoberfest 2024.

**Comment by UppuluriKalyani** [comment]
@Ittismita Go ahead!Make sure you star the repo 🙃

**Comment by Soumya0927** [comment]
Hi @UppuluriKalyani ,
I would like to contribute to this issue. Could you please assign it to me?
Thank you!

**Comment by UppuluriKalyani** [comment]
@Ittismita it's already done by someone I guess you can work on some other open issues mention me there will assign it you
