### ISSUE TITLE
Feature request: Deploy the Movie Recommendation system to Streamlit 

### ISSUE THREAD

**Issue by mjgandhi2305** [UppuluriKalyani/ML-Nexus#544]
**Is your feature request related to a problem? Please describe.**
Yes, currently the system exists only as an IPYNB file, which creates a barrier for user engagement. Deploying it to Streamlit would provide a user-friendly interface, making it easier for users to interact with the recommendation system.

**Describe the solution you'd like**
I would like the Movie Recommendation system to be deployed on Streamlit with an intuitive and easy-to-navigate web interface. The interface should allow users to select or enter details about their preferences and receive movie recommendations based on collaborative filtering and cosine similarity.

**Describe alternatives you've considered**
I considered deploying the system using other platforms like Flask or Django. However, these alternatives would require additional development effort for building and maintaining a web interface. Streamlit offers a simpler, more streamlined solution suitable for deploying data science and machine learning models quickly.

**Approach to be followed (optional)**
Convert the existing IPYNB code into a Python script compatible with Streamlit.
Use Streamlit components like sliders, select boxes, and inputs to allow users to specify their preferences.
Implement the recommendation logic based on collaborative filtering and cosine similarity calculations.
Display the recommended movies in a user-friendly format, using Streamlit features like tables, cards, or images.
Deploy the Streamlit app to Streamlit Cloud or a preferred hosting service.

**Additional context**
Deployment to Streamlit would not only improve accessibility but also provide an interactive experience, leading to increased user engagement and feedback. Any visualizations related to recommendations could also be integrated seamlessly using Streamlit’s built-in plotting features.

**Comment by mjgandhi2305** [comment]
@Neilblaze @SaiNivedh26 please assign this issue to me under hacktoberfest-accepted, level-3 and gssoc-ext

**Comment by UppuluriKalyani** [comment]
@mjgandhi2305 level3? First do it then will assign.

**Comment by UppuluriKalyani** [comment]
@mjgandhi2305 you can raise some good ideas.
