### ISSUE TITLE
Text-to-Speech model

### ISSUE THREAD

**Issue by BhavyaFattania** [UppuluriKalyani/ML-Nexus#56]
Use Cases
Text-to-Speech (TTS) models can be used in any speech-enabled application that requires converting text to speech imitating human voice.
Use Cases
Text-to-Speech (TTS) models can be used in any speech-enabled application that requires converting text to speech imitating human voice.

**Comment by UppuluriKalyani** [comment]
@BhavyaFattania Assigned!
