### ISSUE TITLE
Feature request: creating R program folder and adding Loan Default Prediction Using Decision Trees and Random Forests 

### ISSUE THREAD

**Issue by akashlogics** [UppuluriKalyani/ML-Nexus#561]
**Is your feature request related to a problem? Please describe.**
This project aims to predict loan defaults (or customer churn) using Decision Tree and Random Forest models. We will use financial and demographic information from customers to train machine learning models and predict whether a customer will default on a loan or not.

**Describe the solution you'd like**
We will compare the performance of these models using metrics such as accuracy, precision, recall, and confusion matrices. Additionally, we'll visualize the decision tree and assess feature importance in the random forest model.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
![Screenshot 2024-10-24 110512](https://github.com/user-attachments/assets/dc928938-a034-4270-aee8-6cca2a26e1cd)

**Comment by Soumyals** [comment]
Hey, is this issue resolved. If not, i would love to work on this. I have sufficient expertise in data analytics and R programming. I would like to improve and hence resolve this issue in a better manner. Could you assign this to me.
thank you

**Comment by Soumyals** [comment]
Hey, it was assigned to me yesterday. I am currently working on it. Will share the progress in sometime.
Thank you
