### ISSUE TITLE
Feature request: Hand Game Controller using OpenCV

### ISSUE THREAD

**Issue by aviralgarg05** [UppuluriKalyani/ML-Nexus#58]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Control Vehicles in games Using Hand Movements
**Describe the solution you'd like**
Using OpenCV and Machine Learning techniques, control vehicles using hand Movements
**Describe alternatives you've considered**
N/A
**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.
Model training using videos and then allowing keyboard input
**Additional context**
I am a GSSOC'24 Extended and Hacktoberfest Contributor

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 Go ahead! Please star the repo if you find it helpful
