### ISSUE TITLE
Sign Language Translator

### ISSUE THREAD

**Issue by SaiNivedh26** [UppuluriKalyani/ML-Nexus#59]
Develop an system that uses computer vision to recognize and interpret sign language gestures in ***real-time*** . 
It must be a 2 way translator, that is, 

1. It must convert the Sign gestures to text and Synthesized speech (optional)
2. It must also convert spoken language into visual sign language representations. (here primary language can be considered as English)

> [!NOTE]  
> For your reference, I've already worked on the different variation of the project, where user can upload the document (or) provide You tube video link (or) provide audio/video , where it'll transcribe and map them to different sign languages
Check : https://github.com/SaiNivedh26/ACCESSIBLE-AI-Digital-content-to-sign-language-converter

**Comment by UppuluriKalyani** [comment]
@smartfellow1234 Proceed! Please star the repo if you find it helpful.
And Make sure the implementation should perfectly aligned with the issue.

**Comment by rithvikreddybasani** [comment]
I have some additional features For this to include

AutoCorrection
AutoSuggestion - Natural Language Processing
Translator - Sign to Speech integrating 100 Languages
Male and Female Voice

Can you please assign me this @UppuluriKalyani?

**Comment by SaiNivedh26** [comment]
proceed @rithvikreddybasani !
