### ISSUE TITLE
Lung cancer risk assesment

### ISSUE THREAD

**Issue by ananyag309** [UppuluriKalyani/ML-Nexus#593]
Is your feature request related to a problem? Please describe.
There is a need for an accessible tool to assess lung cancer risk, especially for individuals with varying risk factors like smoking, family history, and occupational exposure.

Describe the solution you'd like
Develop a user-friendly lung cancer risk assessment tool that allows users to input personal health and lifestyle factors, providing a personalized risk score, preventative measures, and screening recommendations.

Describe alternatives you've considered
Existing Online Tools: Limited personalization and comprehensive analysis.
Mobile Apps: Few focus specifically on lung cancer risk.
Healthcare Provider Consultation: Effective but may be costly or inaccessible.

Approach to be followed (optional)
Research: Analyze lung cancer risk factors and existing tools.
Development: Collaborate with medical professionals on a risk assessment algorithm.
User Testing: Refine the tool based on feedback.
Launch: Provide educational resources alongside the tool.

Additional context
This tool could benefit high-risk populations by promoting awareness and early detection strategies, enhancing preventive care efforts.

**Comment by ananyag309** [comment]
@UppuluriKalyani Even this issue is nowhere. Please assign this to me

**Comment by ananyag309** [comment]
hi, the file is too big, even when i convert it to zip, i am unable to upload it.

**Comment by UppuluriKalyani** [comment]
> hi, the file is too big, even when i convert it to zip, i am unable to upload it.

Don't upload dataset just implementation file and readme file and dataset link

**Comment by ananyag309** [comment]
Okay, also this is not level1.
Please resolve that too asap.
Thankyou

**Comment by UppuluriKalyani** [comment]
@ananyag309 how would you say that I know people are just copying from the internet and just pasting here but still accepting, sorry if you raise any issue that's not from internet definitely will give level2 or level3
