### ISSUE TITLE
Enhancement for Cold Email Generator App (Allow users to manually edit the generated email)

### ISSUE THREAD

**Issue by shreyasparaj** [UppuluriKalyani/ML-Nexus#625]
**Is your feature request related to a problem? Please describe.**
Currently, users cannot modify the generated emails, which limits customization and personal touch. This can lead to frustration when users want to adjust the content to better fit their needs or style.

**Describe the solution you'd like**
I propose adding a text area that allows users to manually edit the generated email. Additionally, users should have the option to save the edited email as a draft, download it as a text file, or copy it to the clipboard.

**Describe alternatives you've considered**
An alternative solution could be to allow only minor adjustments to the generated email through predefined templates. However, this would still restrict user creativity and flexibility.

**Approach to be followed (optional)**
Implement a text area component for editing the email content.
Add a button to save the email as a draft in the session state.
Include a download button that exports the edited email as a .txt file.
Provide a streamlit inbuilt button to copy the email content to the clipboard.

**Additional context**
This feature will enhance user experience by providing more control over the email content. It encourages user engagement and ensures the emails can be personalized to better reflect individual communication styles.

**Comment by shreyasparaj** [comment]
@SaiNivedh26 Please assign level for this issue.
@Neilblaze , @UppuluriKalyani

**Comment by UppuluriKalyani** [comment]
@shreyasparaj can you raise good ideas.
