### ISSUE TITLE
Implement Issue Reminder Workflow🚀

### ISSUE THREAD

**Issue by amiya-cyber** [UppuluriKalyani/ML-Nexus#632]
Description: Create a GitHub Actions workflow that sends reminders on open issues without updates for 7 days. The workflow should post a comment prompting assignees to take action.

Expected Benefits:

Improved responsiveness and prioritization of tasks.
Increased overall productivity.

please assign me with level3 label

**Comment by UppuluriKalyani** [comment]
@amiya-cyber do it! But put is as within 5 days
