### ISSUE TITLE
Feature request- voice to text generation with NLP

### ISSUE THREAD

**Issue by AE-Hertz** [UppuluriKalyani/ML-Nexus#648]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
voice to text generation with NLP

**Describe the solution you'd like**
Voice to text generation with the help of natural language processing to convert speech into text.
This feature can help to build a really advanced notepad app and integration apps.

Assign me this issue under gssoc-ext and hacktoberfest

**Comment by UppuluriKalyani** [comment]
@AE-Hertz you should wait until I tell you to do it don't make PR till then

**Comment by AE-Hertz** [comment]
@UppuluriKalyani my bad, I will remember it next time. Thank you.

**Comment by UppuluriKalyani** [comment]
@AE-Hertz already done don't raise already existing issues.
