### ISSUE TITLE
Feature request: Student Performance Prediction 

### ISSUE THREAD

**Issue by AE-Hertz** [UppuluriKalyani/ML-Nexus#653]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Student Performance Prediction with the help of machine learning.

**Describe the solution you'd like**
Develop using skitlearn.

Assign me this under hacktoberfest and gssoc-ext.

**Comment by AE-Hertz** [comment]
@UppuluriKalyani hello let me know if I can work on this and send pr. Thank you

**Comment by UppuluriKalyani** [comment]
@AE-Hertz sorry it's already done #206 
You can try different one.
