### ISSUE TITLE
Website creation

### ISSUE THREAD

**Issue by yashksaini-coder** [UppuluriKalyani/ML-Nexus#666]
@UppuluriKalyani I would like to create a website for this repository to showcase the different projects & lists the different assets used in the machine Learning algorithms. 

The site will be a guide on better introduction & interaction with the other users.

**Comment by yashksaini-coder** [comment]
@UppuluriKalyani @Neilblaze @SaiNivedh26 can you review this PR and assign it to me, also I would require longer than usual to complete a deployable site using the Github Pages.

**Comment by UppuluriKalyani** [comment]
@yashksaini-coder i think someone already raised it, if you can build cool website then will see.
