### ISSUE TITLE
ADD Yahoo Answer NLP

### ISSUE THREAD

**Issue by ananyag309** [UppuluriKalyani/ML-Nexus#68]
Goal
The goal of this project is to create a deep learning model to analyse the Yahoo Answers.

Dataset
The dataset for this project is taken from the Kaggle dataset website. Here is the link for the dataset: https://www.kaggle.com/datasets/yacharki/yahoo-answers-10-categories-for-nlp-csv

**Comment by SaiNivedh26** [comment]
@ananyag309 Do you want to perform Sentiment analysis of the yahoo answers ? 
Provide worked code files. Along with that attach the results which you got and provide necessary evaluation metrices as well

**Comment by SaiNivedh26** [comment]
start working ! @ananyag309

**Comment by Neilblaze** [comment]
@ananyag309 bumping this up, is there any progress on this?

**Comment by ananyag309** [comment]
I am sorry for not being able to be active on this issue, I am quite occupied with my sem exam since starting of the month. My one more exam is left. But I will try to raise pr asap
