### ISSUE TITLE
End-to-end Multil-class Dog Breed Classification

### ISSUE THREAD

**Issue by Pranshu-jais** [UppuluriKalyani/ML-Nexus#71]
🔴 Dataset : https://www.kaggle.com/c/dog-breed-identification/data

🔴 Approach : Building and training Multil-class Dog Breed Classification deeplearning model to classify breed breed of a dog 

please assign this issue to me under gssoc - ext 2024 with appropriate level

**Comment by SaiNivedh26** [comment]
@Pranshu-jais Start working !

Provide a pipeline of the work which you're gonna do and upload the necessary files. if it's verified, it'll be merged with main branch

**Comment by Pranshu-jais** [comment]
> @Pranshu-jais Start working !
> 
> Provide a pipeline of the work which you're gonna do and upload the necessary files. if it's verified, it'll be merged with main branch

The goal of this project is to create a convolutional neural network (CNN) that can classify images of dogs into their respective breeds. It leverages   convolutional neural network (CNN) architectures, including mobilenet_v2 as the base and fine-tuning it on the dog breed dataset. The model architecture includes several convolutional layers followed by fully connected layers.
