### ISSUE TITLE
Bug report: Workflow run failed for main branch

### ISSUE THREAD

**Issue by Soumya0927** [UppuluriKalyani/ML-Nexus#724]
Hi, @UppuluriKalyaniI
I have been receiving notifications regarding this issue every day, and so far, I have received four reminders. I wanted to clarify whether this is an issue from your side or mine.

If it is from my side, I would appreciate your guidance on how to rectify it. Thank you for your assistance.

![image](https://github.com/user-attachments/assets/b281b486-387a-4b22-bf8a-b2acd55abfff)

**Comment by UppuluriKalyani** [comment]
@Soumya0927 yeah it's from my side don't worry
