### ISSUE TITLE
Image captioning Using Ai 

### ISSUE THREAD

**Issue by Manishkumarsingh41** [UppuluriKalyani/ML-Nexus#728]
I’m interested in contributing to the ML-Nexus project, specifically in the area of image captioning, where users can upload images to generate captions , as part of GSSoC. Could you please consider appointing me to contribute to this repository under the program? I believe my skills align well with the project’s needs, and I’m eager to make a meaningful contribution.

**Comment by UppuluriKalyani** [comment]
@Manishkumarsingh41 already done
