### ISSUE TITLE
Improve the Main hero section  

### ISSUE THREAD

**Issue by yashksaini-coder** [UppuluriKalyani/ML-Nexus#736]
The current Hero section is lacking and I am planning to add custom CSS animations effect on user hovering, would add new custom assets if possible

![image](https://github.com/user-attachments/assets/95fd8ef4-0f52-4c34-b156-a3628aaae2be)

**Comment by UppuluriKalyani** [comment]
@yashksaini-coder yeah you can enhance everything will add levels on PR and add animations too if possible can we get blue theme instead of green.

**Comment by yashksaini-coder** [comment]
@UppuluriKalyani kindly assign this issue to @mehul-m-prajapati, as I can't work on it anymore

**Comment by mehul-m-prajapati** [comment]
@UppuluriKalyani - please assign it to me
