### ISSUE TITLE
Recreaitng the Footer section

### ISSUE THREAD

**Issue by yashksaini-coder** [UppuluriKalyani/ML-Nexus#737]
The current footer section is not proper & is lacking a lot of content & proper concepts that a website should has
- About US page
- Projects page
- Contact US page

I aim to add those pages

---

![image](https://github.com/user-attachments/assets/49295147-ad3c-4699-94b1-754a90a5d25d)

**Comment by yashksaini-coder** [comment]
@UppuluriKalyani kindly assign this issue to @mehul-m-prajapati, as I can't work on it anymore

**Comment by mehul-m-prajapati** [comment]
@UppuluriKalyani - please assign it to me
