### ISSUE TITLE
Add new Computer Vision Project Self Driving Car

### ISSUE THREAD

**Issue by karthikyandrapu** [UppuluriKalyani/ML-Nexus#744]
**Is your feature request related to a problem? Please describe.**
The current implementation performs lane detection on video frames using Canny edge detection and Hough line transformations. However, the accuracy of lane detection decreases when the video has low visibility (such as nighttime driving or adverse weather). Additionally, there is no adaptive thresholding to handle varying brightness levels, which could improve detection accuracy.

**Describe the solution you'd like**
An adaptive thresholding technique for Canny edge detection could be implemented to adjust thresholds dynamically based on the brightness level of each frame. Additionally, introducing a weighted average on lane lines over several frames could reduce noise and improve line stability, particularly when there are rapid brightness changes.

**Screenshots:**
![findingLanes](https://github.com/user-attachments/assets/b189477b-85c2-4cd5-bdb9-39ab4f1a35a2)
![cannyEdgeDetection](https://github.com/user-attachments/assets/81b9bdc9-f658-43db-8bc4-622dcd8b5248)

**Describe alternatives you've considered**
- Implementing Sobel edge detection, which could provide more robust edge information in complex lighting conditions.
- Applying a deep learning-based lane detection model for more accurate lane line detection across different road environments, although this would increase computational overhead.

**Approach to be followed (optional)**
- Modify the canny function to include adaptive thresholding based on frame brightness.
- Enhance the average_slope_intercept function to calculate a weighted average over multiple frames, stabilizing the lane lines.
- Experiment with Sobel edge detection as a comparison, and decide if the improvement justifies switching from Canny.
 
**Additional context**
The current code uses Hough line transformations to detect lane lines, but adding adaptive thresholding and frame averaging could make it more effective across various driving conditions.

**Comment by UppuluriKalyani** [comment]
@karthikyandrapu lane detection already done, before raising please check whether they are existed or not
