### ISSUE TITLE
Feature request Adding a NLP model of Grammar AutoCorrector

### ISSUE THREAD

**Issue by Peart-Guy** [UppuluriKalyani/ML-Nexus#748]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
I would like to add a  Grammar AutoCorrector Model

A grammar autocorrector model helps users write clearly and professionally by correcting errors instantly. It saves time, boosts confidence, and aids learning by showing suggested improvements.

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Comment by UppuluriKalyani** [comment]
@Peart-Guy already done #108
