### ISSUE TITLE
Feature request: Add sliding effect when a user hovers over or interacts with the Hot topic cards

### ISSUE THREAD

**Issue by mehul-m-prajapati** [UppuluriKalyani/ML-Nexus#750]
**Describe the solution you'd like**
-  Add sliding effect when a user hovers over or interacts with the Hot topic cards
- Also, add some more topics in list

![s1](https://github.com/user-attachments/assets/0822d2c8-ff5f-4b3f-9fd4-0115b2500299)

**Comment by UppuluriKalyani** [comment]
@mehul-m-prajapati proceed
