### ISSUE TITLE
Add a new Project called as "Image-to-3D model"

### ISSUE THREAD

**Issue by NANDAGOPALNG** [UppuluriKalyani/ML-Nexus#758]
Our Project is called as VFusion3D, it is a large, feed-forward 3D generative model trained with a small amount of 3D data and a large volume of synthetic multi-view data. It is the first work exploring scalable 3D generative/reconstruction models as a step towards a 3D foundation.

**Comment by UppuluriKalyani** [comment]
@NANDAGOPALNG already done before raising issues please check whether they are existed or not
