### ISSUE TITLE
Classification of emotions in images and videos

### ISSUE THREAD

**Issue by Pranshu-jais** [UppuluriKalyani/ML-Nexus#77]
**Is your feature request related to a problem? Please describe.**
The current system lacks the ability to accurately classify emotions in video and images, which is crucial for applications in mental health monitoring, customer service, and human-computer interaction. Existing methods often fail to capture the nuances of human emotions, leading to inaccurate or unreliable results.

**Describe the solution you'd like**
I propose developing a convolutional neural network (CNN) model that can accurately classify emotions in video and images. This model will be trained on a diverse dataset to recognize a wide range of emotions, improving the accuracy and reliability of emotion classification. The solution should integrate seamlessly with existing systems and provide real-time emotion detection.

please assign this issue to me under gssoc-ext  2024

**Comment by UppuluriKalyani** [comment]
@Pranshu-jais Proceed!
