### ISSUE TITLE
Feature request-Spam mail Prediction (with app.py)

### ISSUE THREAD

**Issue by Shy029** [UppuluriKalyani/ML-Nexus#778]
I propose adding a "Spam Mail Detection" feature to the ML Nexus project, which is not currently included. This feature will utilize machine learning to classify emails as spam or non-spam and will be built with a user-friendly `app.py` interface to allow real-time interaction. Users will input email text directly into the app, which will then instantly classify the email. This feature would enhance ML Nexus by providing a practical, widely applicable tool for email filtering, further broadening the project's utility and real-world application value. I am excited to contribute to ML Nexus by implementing this essential feature.

Please assign this to me.

**Comment by UppuluriKalyani** [comment]
@Shy029 please raise ideas which are not existed
