### ISSUE TITLE
Butterfly Image Classification using deep learning

### ISSUE THREAD

**Issue by IkkiOcean** [UppuluriKalyani/ML-Nexus#78]
- 🎯 Goal
The primary goal of this project is to build and compare various deep learning models to accurately classify butterfly images into their respective species.

- 🧾 Description

This dataset consists of over 1000 labeled images of butterflies, including validation images. Each image belongs to only one butterfly category. The challenge is to develop models that can accurately classify these images into the correct species.

- 🚀 Models Implemented
      - Convolutional Neural Network (CNN)
      - EfficientNet
      - ResNet50

Please assign me this under GSSOC-extd and hacktoberfest

**Comment by SaiNivedh26** [comment]
@IkkiOcean  Start working !

Provide a pipeline of the work which you're gonna do and upload the necessary files. if it's verified, it'll be merged with main branch
