### ISSUE TITLE
Iris Flower Classification

### ISSUE THREAD

**Issue by aviralgarg05** [UppuluriKalyani/ML-Nexus#79]
**Is your feature request related to a problem? Please describe.**
Iris Flower Classification using OpenCV

**Describe the solution you'd like**
Use OpenCV and ML algos to perform iris flower classification

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
Data Collection, EDA, Preprocess, Training and Testing

**Additional context**
I am a GSSOC'24 Extended Contributor and Hacktoberfest Contributor

**Comment by aviralgarg05** [comment]
I would be collecting the data and the perform pre-processing, training and testing will also be done.

**Comment by ReaganBlade** [comment]
@SaiNivedh26 
Hello, I'm working on this issue and I've Created a classification model using Regression. It's a Streamlit app. I'll be sending a pull request. Please Accept it. 

I'm a hacktoberfest & GSSoC'24 Contributor
