### ISSUE TITLE
✨ Feature Request: Real-Time Multilingual Translation with Speech-to-Text & Text-to-Speech Integration 🌍

### ISSUE THREAD

**Issue by 770navyasharma** [UppuluriKalyani/ML-Nexus#80]
This repository is an absolute gem for those diving into machine learning and working on innovative projects. 🚀 To make it even more powerful, I'd love to contribute by adding a real-time translation model covering more than 10 languages—focusing especially on Indian regional languages. This feature will include both speech-to-text and text-to-speech integrations, all wrapped in an interactive Streamlit app for seamless user experience.

What will this feature add?
🔄 Real-Time Translation across multiple languages.
🎤 Speech-to-Text: Users can speak in their native language, and the model will transcribe the audio in real-time.
🗣️ Text-to-Speech: The translated text can also be played back in the target language.
🌐 Focus on Indian regional languages to cater to a diverse audience.
🎛️ User-Friendly Interface using Streamlit for smooth interaction and accessibility.
How I Plan to Build This:
Implement a multilingual model capable of real-time translation using state-of-the-art NLP techniques.
Integrate Speech-to-Text using APIs such as Google Cloud Speech or Whisper.
Add Text-to-Speech support for multiple languages using libraries like gTTS or Azure Speech.
Deploy the solution on Streamlit, making it easily accessible via web for demo purposes.
Why This Matters:
Machine learning is not just about models but also about making them accessible and practical for everyday users. A real-time translation app opens doors for cross-language communication, helping people connect in ways never imagined before. 🌏 Plus, focusing on Indian languages will promote inclusivity and bridge the linguistic gap in technology.

💡 I’m excited to work on this! Kindly assign me this task under the following tags:

hacktoberfest 🎉
gssoc 👩‍💻
level 📈
Looking forward to contributing and taking this repository to the next level! 💪

cc: @UppuluriKalyani

**Comment by Neilblaze** [comment]
@770navyasharma I'm binding with @SaiNivedh26's suggestion. Also, just to add context as reference, OpenAI does ship their own variant of tts (possibly [tts-1](https://platform.openai.com/docs/models/tts) can be utilized here), but it's extensively resource constrained (`EN`, `HI`, `BN`, & a few) and lacks a diverse range of indic-languages. So, [Azure AI Speech](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts#supported-languages) is a better fit, but it takes a bit longer time to process.

While, for the first section of pipeline, you'll have to benchmark which whisper's s2t (model variant) will be better, as there you might have to compromise with inference speed and processing accuracy.

**Comment by 770navyasharma** [comment]
@SaiNivedh26 At a base level I made a basic translator model using google translate and gtts which actually provides support for various indian languages Here is the demo of the result .

![Screenshot 2024-10-04 232059](https://github.com/user-attachments/assets/af8429f6-3e83-4f48-9418-63f3bdf7b8da)
![Screenshot 2024-10-04 232107](https://github.com/user-attachments/assets/13d39190-50bf-40e8-ad66-2a61b1eb9ee8)

**Comment by SaiNivedh26** [comment]
@770navyasharma Proceed to PR. Will review the files in that and let you know about merging it with main branch. But make sure to attach a .README file to discuss in detail about your structure and The result which you've obtained
