### ISSUE TITLE
Implement CNN for Traffic Sign Recognition using GTSRB Dataset

### ISSUE THREAD

**Issue by ojhankit** [UppuluriKalyani/ML-Nexus#82]
**Description:**
I would like to propose the implementation of a Convolutional Neural Network (CNN) for traffic sign recognition, utilizing the German Traffic Sign Recognition Benchmark (GTSRB) dataset. This project aims to develop a robust model that can accurately classify traffic signs, which is crucial for applications in self-driving cars and enhancing road safety.

**Background:**
The GTSRB dataset consists of over 50,000 images of traffic signs belonging to 43 classes. By using a CNN architecture, we can create a model that not only classifies these signs but also provides insights into the feature extraction process, enhancing the understanding of how different traffic signs are recognized by machine learning models.

**Request for Feedback**
I am seeking feedback on this proposal and would like to work on this.
Assign this to me.

**Comment by ojhankit** [comment]
@UppuluriKalyani assign this to me

**Comment by UppuluriKalyani** [comment]
@ojhankit Assigned!
