### ISSUE TITLE
Feature request: Creation of Markdown Files for Basic ML Algorithms

### ISSUE THREAD

**Issue by shrek-28** [UppuluriKalyani/ML-Nexus#85]
Is your feature request related to a problem? Please describe.
There is currently no clear documentation or explanation within the project to help users understand fundamental machine learning algorithms like Linear Regression and Logistic Regression. This lack of documentation can make it harder for new contributors or users to grasp how these algorithms work in the context of the project.

Describe the solution you'd like
Create markdown files that provide clear and concise explanations of key machine learning algorithms, starting with Linear Regression and Logistic Regression. These markdowns should include mathematical formulas, basic code snippets, and real-world applications to help users understand the concepts and their implementation.

Describe alternatives you've considered
Alternatives could include embedding explanations directly in the codebase as comments or linking to external resources. However, these solutions may not be as accessible or tailored to the project’s specific use cases as a set of dedicated markdown files.

Approach to be followed (optional)
Create separate markdown files for each algorithm (e.g., linear_regression.md and logistic_regression.md).
Include clear explanations of the algorithms, equations, basic Python code examples, and diagrams where applicable.
Ensure the markdowns are linked from the README.md or a dedicated documentation section.

**Comment by JahnaviDhanaSri** [comment]
Hi @shrek-28,

I am excited about the opportunity to contribute to this project! I believe that creating dedicated markdown files for fundamental machine learning algorithms is essential for enhancing documentation and aiding new users. I have a strong understanding of Linear Regression and Logistic Regression, and I can create clear explanations, mathematical formulations, and practical code snippets for these algorithms.

Could you please assign this issue to me?

**Comment by JahnaviDhanaSri** [comment]
Hi @shrek-28,

I appreciate the initiative to enhance documentation for fundamental machine learning algorithms! Clear explanations of algorithms like Linear Regression and Logistic Regression are essential for new contributors and users.

I would love to take on this task and create the markdown files. My plan includes:

Detailed explanations of each algorithm, including mathematical formulas and real-world applications.
Basic Python code snippets to demonstrate implementation.
Diagrams to visualize key concepts where applicable.
Additionally, I will ensure that these markdown files are properly linked in the README.md for easy access.

Could you please assign this issue to me?
