### ISSUE TITLE
Feature request:  Dog Breeds Classification

### ISSUE THREAD

**Issue by IkkiOcean** [UppuluriKalyani/ML-Nexus#88]
- **Title :** Dog Breeds Classification
-  **Aim : **The goal of this project is to develop a machine learning model that accurately classifies dog breeds based on their images. Given a dataset of labeled dog images, the task is to predict the correct breed for each image.
- **Brief Explanation :**
The primary objective of this project is to accurately classify dog breeds from images using advanced deep learning techniques. By leveraging state-of-the-art convolutional neural network (CNN) architectures, including ResNet50V2, MobileNet, and VGG19, I aim to develop a model capable of predicting the correct breed label for each input image.

**Dataset:** https://www.kaggle.com/datasets/gpiosenka/70-dog-breedsimage-data-set

**Full name :** Vivek Prakash

**Program: GSSOC-extd and hacktoberfest**

**Comment by UppuluriKalyani** [comment]
@IkkiOcean Proceed!
