### ISSUE TITLE
Real-Time Object Tracking and Deepfake Detection

### ISSUE THREAD

**Issue by AwnishRanjan** [UppuluriKalyani/ML-Nexus#90]
**Is your feature request related to a problem? Please describe.**
project is based on real time Tracking system based on the base model of Yolo , I have deployed 2 models there and done deep fake detection upon that.

some interesting features are : realtime path creation which moves in the video/ camera feed.

**Describe the solution you'd like**
using Yolo we can track the frames and using calamine filters we can track predict the next frame using physics laws. 

**Describe alternatives you've considered**
we can do it using LIMs as well but I will not go for direct approach rather than I will more prefer to create it from a base level.

**Comment by UppuluriKalyani** [comment]
@AwnishRanjan Proceed! Please star the repo
